### ISSUE TITLE
Provide optional kwarg to questions specifying a value if the question is not asked

### ISSUE THREAD

**Issue by fhightower** [wayfair-incubator/columbo#165]
I propose we add an optional kwarg to the questions (`BasicQuestion`, `Choice`, and `Confirm`) which allows users to specify a value if the question is not asked. I suggest this kwarg be named `value_if_not_asked` (but I'm open to other suggestions). Below, I propose *what* this new functionality might look like and *why* it's valuable.

# Current Functionality

Consider the following code:

```python
import columbo

interactions = [
    columbo.Confirm(
        "eats",
        "Do you eat to sustain life?"
    ),
    columbo.Confirm(
        "carnivore",
        "Do you eat meat?",
        should_ask=lambda answers: answers["eats"]
    )
]

columbo.get_answers(interactions)
```

If the user answers "No" to the `eats` question, the `carnivore` question will not be asked and the answers will *not* include a `'carnivore'` key:

```python
{'eats': False}
```

# Proposed Functionality

When implemented, my suggested `value_if_not_asked` kwarg would look like:

```python
import columbo

interactions = [
    columbo.Confirm(
        "eats",
        "Do you eat to sustain life?"
    ),
    columbo.Confirm(
        "carnivore",
        "Do you eat meat?",
        should_ask=lambda answers: answers["eats"],
        value_if_not_asked=False
    )
]

columbo.get_answers(interactions)
```

If the user answers "No" to the `eats` question, the `carnivore` question will not be asked *but...* the answers will include a `'carnivore'` key:

```python
{'eats': False, 'carnivore': False}
```

# Why?

This feature will be valuable because it allows users to guarantee that there is a key-value pair for each question (which is currently not the case as noted in the `Warning` [here](https://wayfair-incubator.github.io/columbo/latest/usage-guide/optional-questions-and-branching/#only-asking-some-questions)). There are many use-cases when it is very helpful to guarantee that there is a key-value pair for each question without having to either ask the user every question or write additional checks to see if a key is present before evaluating it (e.g. when using Columbo to populate cookiecutter templates as is being done [here](https://github.com/cookiecutter-flask/cookiecutter-flask)).

# Implementation Details

### What if the `value_if_not_asked` field is present without `should_ask`?

In this case, the question will be asked and the `value_if_not_asked` will be ignored.

### What are the type restrictions on the type of the `value_if_not_asked`?

The type of the `value_if_not_asked` will be the same as the type of answer and will be validated. So if `value_if_not_asked` is used for a `Confirm` question, it must be a boolean. If it is used for a `BasicQuestion`, it must be a string. If it is used for a `Choice`, it must be a string that is one of the options.

Any thoughts on this feature?

**Comment by plannigan** [comment]
I think this is a good addition. My only comment would be to raise an error instead of silently ignoring `value_if_not_asked` being passed in when it would not be used.

**Comment by fhightower** [comment]
That makes sense, I'll implement that. Todo:

- [ ] write tests
- [ ] implement feature
- [ ] update docs
