### ISSUE TITLE
Support `should_ask` in `Echo` interaction

### ISSUE THREAD

**Issue by mklaber** [wayfair-incubator/columbo#356]
Feature request: conditionally display `Echo` interactions similar to how `BasicQuestion`, `Confirm`, etc. work. This would allow us to display text conditionally based on responses to previous questions.

> Confirm you like dogs? [y/N]
> <kbd>y</kbd>
> Great, now that we know you like dogs, here are some things you'll need to know:
> * Unlike cats, dogs actually like you
> * Unlike cats, dogs don't plot ways to kill you in your sleep
> 
> What breed of dog do you prefer? [English Setter]

**Comment by plannigan** [comment]
That seems like a reasonable request. It could even be added to `Acknowledge` to make things more symmetrical.
