### ISSUE TITLE
Remove Legacy Validator

### ISSUE THREAD

**Issue by plannigan** [wayfair-incubator/columbo#40]
Complete the deprecation process of the legacy `Validator` signature. Remove support from the code base and references from the code base.

**Comment by atruslow** [comment]
@plannigan can you please provide some more detail on what deprecating the validator signature entails?

RIght now the Validator signature is the following `Validator = Callable[[str, Answers], Union[ValidationResponse, Optional[str]]]`, and it is used in `BasicQuestion`.

**Comment by atruslow** [comment]
@plannigan Just put up this PR for this change -> https://github.com/wayfair-incubator/columbo/pull/123

**Comment by fhightower** [comment]
@plannigan : I think this should be tied to the 1.0.0 milestone. Is that correct?

**Comment by plannigan** [comment]
Yeah. I think I saw the pattern of removing deprecated things in the first minor after the major in `pytest`. But since there isn't anything else new being added, there isn't the selling point of "Update to X+1.0.0 to get these benefits".
