### ISSUE TITLE
Pre-Release support for version bump detection

### ISSUE THREAD

**Issue by plannigan** [wayfair-incubator/columbo#74]
The workflow that detects a version bump will trigger a new release for the repo. However, if the new version is not a final version (alpha, beta, etc.), the github release should be marked as a pre-release.

**Comment by fhightower** [comment]
To give more color this issue: update the `detect_version_bump.yml` workflow as mentioned [here](https://github.com/wayfair-incubator/columbo/pull/69/files#r568830314) to have set the `prerelease ` (one of the [inputs](https://github.com/actions/create-release#inputs) for the create-release action) input set based on whether a new version is a prerelease or not.
