### ISSUE TITLE
Error when trying to bump package version: "git: 'switch' is not a git command."

### ISSUE THREAD

**Issue by fhightower** [wayfair-incubator/columbo#95]
When publishing the package with `docker-compose run --rm bump minor` (per the [docs](https://wayfair-incubator.github.io/columbo/latest/development-guide/#publishing-the-package)), I get this error:

```
git: 'switch' is not a git command.
```

This is because the docker container has git version `2.20.1` while `git switch` was added in `2.23.0` (https://git-scm.com/docs/git-switch/2.23.0).

**Comment by plannigan** [comment]
Have you pulled latest to pull in this change? #94

**Comment by fhightower** [comment]
Yes, I have.

**Comment by plannigan** [comment]
Oh, I see now. It is a different git command that is failing now.
